[package]
name = "cargo-mate"
version = "0.1.0"
authors = ["Cameron Low <email>", "Luca Carlig <luca.carlig@huawei.com"]
description = "description goes here"
edition = "2021"
publish = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "b105fb4c39bc1a010807a6c076193cef8d93c109" }
dylint_linting = "2.5.0"
if_chain = "1.0.2"


[dev-dependencies]
dylint_testing = "2.5.0"
rayon = "1.8"

[package.metadata.rust-analyzer]
rustc_private = true
