[package]
name = "cargo-mate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "cargo-mate"
test = false
path = "src/main.rs"

[dependencies]
if_chain = "1.0.2"
rustc-tools = "0.2.1"
clippy_utils = { path = "clippy_utils" }
clap = { version = "4.4.10", features = ["derive", "cargo"] }
cargo = "0.75.1"
anyhow = "1.0.75"
rustfix = "0.6.1"


[package.metadata.rust-analyzer]
# This package uses #[feature(rustc_private)]
rustc_private = true
