[package]
name = "cargo-mate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
if_chain = "1.0.2"
rustc-tools = "0.2.0"
clippy_utils = { path = "clippy_utils" }
clap = { version = "4.4.8", features = ["derive", "cargo"] }
toml = "0.8.8"
