[package]
name = "mate"
version = "0.1.0"
authors = ["Cameron Low <email>", "Luca Carlig <luca.carlig@huawei.com"]
description = "library of lints for automatic parallelization"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
for_each = { path = "lints/for_each", features = ["rlib"] }
filter = { path = "lints/filter", features = ["rlib"] }
fold = { path = "lints/fold", features = ["rlib"] }
par_fold = { path = "lints/par_fold", features = ["rlib"] }
dylint_linting = { version = "2.5.0" }

[package.metadata.rust-analyzer]
rustc_private = true

[workspace]
members = [
    "lints/for_each",
    "lints/filter",
    "lints/fold",
    "lints/par_fold",
    "utils",
]

[dev-dependencies]
dylint_testing = "2.5.0"

[workspace.dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "b105fb4c39bc1a010807a6c076193cef8d93c109" }
utils = { path = "utils" }

[workspace.metadata.dylint]
clibraries = [{ path = "../mate" }]
