[package]
name = "cargo-mate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-tools = "0.1.2"
if_chain = "1.0"
# clippy_utils = { path = "clippy_utils" }
