name: bench-test
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  request:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    name:  request_request lint fix passes
    steps:

      - name: clone repo
        run: git clone https://gitee.com/openharmony/request_request.git

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: add Cargo.toml dylint lib link
        run: |
          cd request_request
          echo -e "\n[workspace.metadata.dylint]\nlibraries = [\n    { git = \"https://github.com/trusted-programming/cargo-mate\"},\n]" >> Cargo.toml

      - name: add rayon
        run: |
          cd request_request
          cargo add rayon --package request
          cargo add rayon --package download_server
      
      - name: lint fix
        run: |
          cd request_request
          cargo dylint --all --workspace --fix

  commonlibrary:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    name: commonlibrary_rust_ylong_runtime lint fix passes
    steps:

      - name: clone repo
        run: git clone https://gitee.com/openharmony/commonlibrary_rust_ylong_runtime.git

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: add Cargo.toml dylint lib link
        run: |
          cd commonlibrary_rust_ylong_runtime
          echo -e "\n[workspace.metadata.dylint]\nlibraries = [\n    { git = \"https://github.com/trusted-programming/cargo-mate\"},\n]" >> Cargo.toml

      - name: add rayon
        run: |
          cd commonlibrary_rust_ylong_runtime
          cargo add rayon --package ylong_runtime
          cargo add rayon --package ylong_ffrt
          cargo add rayon --package ylong_io
          cargo add rayon --package ylong_runtime_macros
      
      - name: lint fix
        run: |
          cd commonlibrary_rust_ylong_runtime
          cargo dylint --all --workspace --fix
        
