name: bench-test
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tar:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    name: tar-rs lint fix passes
    steps:
      - uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          repository: "alexcrichton/tar-rs"
      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: add Cargo.toml dylint lib link
        run: echo -e "\n[workspace.metadata.dylint]\nlibraries = [\n    { git = \"https://github.com/trusted-programming/cargo-mate\"},\n]" >> Cargo.toml

      - name: lint fix
        run: |
          count=0

          while [ $count -lt 4 ]; do
              echo "#############################"
              echo "WARNINGS ON STEP $count"
              cargo dylint --workspace --all 2>&1 | grep -i 'warning' | grep -iv 'generated' | sort | uniq -c | sort -nr
              cargo dylint --all --workspace --fix -- --allow-dirty

              ((count++))

          done

  commonlibrary:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    name: commonlibrary_rust_ylong_runtime lint fix passes
    steps:

      - name: clone repo
        run: git clone https://gitee.com/openharmony/commonlibrary_rust_ylong_runtime.git

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: add Cargo.toml dylint lib link
        run: |
          cd commonlibrary_rust_ylong_runtime
          echo -e "\n[workspace.metadata.dylint]\nlibraries = [\n    { git = \"https://github.com/trusted-programming/cargo-mate\"},\n]" >> Cargo.toml

      - name: lint fix
        shell: bash
        run: |
          cd commonlibrary_rust_ylong_runtime
          count=0

          while [ $count -lt 4 ]; do
              echo "#############################"
              echo "WARNINGS ON STEP $count"
              cargo dylint --workspace --all 2>&1 | grep -i 'warning' | grep -iv 'generated' | sort | uniq -c | sort -nr
              cargo dylint --all --workspace --fix -- --allow-dirty 

              ((count++))

          done
        
