name: bench-test
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  request_request:
    runs-on: ubuntu-latest
    name:  request_request
    steps:
      - name: clone repo
        run: git clone https://gitee.com/openharmony/request_request.git

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: add Cargo.toml dylint lib link
        working-directory: ./request_request
        run: echo -e "\n[workspace.metadata.dylint]\nlibraries = [\n    { git = \"https://github.com/trusted-programming/cargo-mate\"},\n]" >> Cargo.toml

      - name: add rayon
        working-directory: ./request_request
        run: |
          cargo add rayon --package request
          cargo add rayon --package download_server
      
      - name: lint fix
        working-directory: ./request_request
        continue-on-error: true
        run:  cargo dylint --all --workspace --fix -- --allow-dirty --allow-no-vcs --broken-code
        
      - name: cargo check
        working-directory: ./request_request
        run: cargo check




  commonlibrary_rust_ylong_runtime:
    runs-on: ubuntu-latest
    name: commonlibrary_rust_ylong_runtime
    steps:
      - name: clone repo
        run: git clone https://gitee.com/openharmony/commonlibrary_rust_ylong_runtime.git

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: add Cargo.toml dylint lib link
        working-directory: ./commonlibrary_rust_ylong_runtime
        run: echo -e "\n[workspace.metadata.dylint]\nlibraries = [\n    { git = \"https://github.com/trusted-programming/cargo-mate\"},\n]" >> Cargo.toml

      - name: add rayon
        working-directory: ./commonlibrary_rust_ylong_runtime
        run: |
          cargo add rayon --package ylong_runtime
          cargo add rayon --package ylong_ffrt
          cargo add rayon --package ylong_io
          cargo add rayon --package ylong_runtime_macros
      
      - name: lint fix
        working-directory: ./commonlibrary_rust_ylong_runtime
        continue-on-error: true
        run:  cargo dylint --all --workspace --fix -- --allow-dirty --allow-no-vcs --broken-code
        
      - name: cargo check
        working-directory: ./commonlibrary_rust_ylong_runtime
        run: cargo check