name: Verify
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  toolchain: nightly-2023-11-16

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain }}

      - name: Install dylint
        run: |
          cargo install cargo-dylint dylint-link

  fmt:
    name: cargo fmt
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    name: cargo clippy
    needs: common
    env:
      RUSTFLAGS: -D warnings
    runs-on: ubuntu-latest
    steps:
      - name: cargo clippy
        run: cargo clippy --lib --all-features

  test:
    name: cargo test
    needs: common
    runs-on: ubuntu-latest
    steps:
      - name: cargo test
        run: cargo test --workspace
