name: Verify
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: stable / fmt
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install nightly-2023-10-06
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2023-10-06
          components: rustfmt

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: cargo fmt --check
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / clippy
    env:
      RUSTFLAGS: -D warnings

    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly-2023-10-06]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: cargo clippy
        run: cargo clippy --all-targets --all-features

  test:
    runs-on: ubuntu-latest
    name: ${{ matrix.toolchain }} / test

    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        toolchain: [nightly-2023-10-06]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - name: install dylint
        run: cargo install cargo-dylint dylint-link

      - name: cargo test
        run: cargo test 
